apiVersion: v1
kind: Service
metadata:
  name: poozle-controller-svc
spec:
  type: NodePort
  ports:
    - port: 3000
      protocol: TCP
  selector:
    poozle: controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poozle-controller
spec:
  serviceAccountName: poozle-admin
  automountServiceAccountToken: true
  replicas: 1
  selector:
    matchLabels:
      poozle: controller
  template:
    metadata:
      labels:
        poozle: controller
    spec:
      containers:
        - name: poozle-controller-container
          image: poozle/controller
          env:
            - name: POOZLE_VERSION
              valueFrom:
                configMapKeyRef:
                  name: poozle-env
                  key: POOZLE_VERSION
          ports:
            - containerPort: 3000
      nodeSelector:
        role: core
