apiVersion: v1
kind: ServiceAccount
metadata:
  name: poozle-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: poozle-admin-role
rules:
  - apiGroups: ["*"]
    # resources: ["jobs", "pods", "pods/log", "pods/exec", "pods/attach", "deployments", "services"]
    resources: ['*']
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] # over-permission for now
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: poozle-admin-binding
roleRef:
  apiGroup: ""
  kind: Role
  name: poozle-admin-role
subjects:
  - kind: ServiceAccount
    name: poozle-admin
