apiVersion: v1
kind: Service
metadata:
  name: poozle-webapp-svc
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    poozle: webapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: engine
  name: poozle-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      poozle: webapp
  template:
    metadata:
      labels:
        poozle: webapp
    spec:
      containers:
        - name: poozle-webapp-container
          image: poozlehq/engine-webapp
          imagePullPolicy: Always
          env:
            - name: NEXT_PUBLIC_BASE_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: poozle-env
                  key: NEXT_PUBLIC_BASE_SERVER_URL
            - name: NEXT_PUBLIC_VERSION
              valueFrom:
                configMapKeyRef:
                  name: poozle-env
                  key: NEXT_PUBLIC_VERSION
          ports:
            - containerPort: 3000
      # nodeSelector:
      #   role: core
