name: Integration Issue
description: Use this when you're facing issue with integration
title: "Integration Issue: "
labels: [type/bug, integration, needs-triage]
body:
  - type: input
    id: integration-name
    attributes:
      label: Integration Name
      description: Give the integration name in form of google-admin, slack
    validations:
      required: true
  - type: input
    id: integration-version
    attributes:
      label: Integration Version
      description: Give the integration version you're using.
    validations:
      required: true
  - type: dropdown
    id: step
    attributes:
      label: What step the error happened?
      multiple: false
      options:
        - Configuring a new integration
        - During the execution of API
        - Updating the integration
        - Other
  - type: textarea
    id: description
    attributes:
      label: Revelant information
      description: Please give any aditional information you have your steps to reproduce the problem.
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste any relevant log output. 
        This will be automatically formatted into code, so no need for backticks.
        We strongly recommend to upload the log file to further debugging.
      render: shell
  - type: checkboxes
    id: submit-pr
    attributes:
      label: Contribute
      description: Are you willing to submit the fix?
      options:
        - label: Yes, I want to contribute
          required: false
