name: New Integration Request
description: Use this to request a new integration
title: "New Integration Request: "
labels: [integration, new-integration]
body:
  - type: input
    id: integration-name
    attributes:
      label: Integration Name
      description: What is the service or database you want to integrate
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Revelant Information
      description: >-
        Why do you need this integration? How does your team intend to use the data? This helps us understand the use case.
        If this is an API which has openAPI spec kindly share the link.
  - type: checkboxes
    id: submit-pr
    attributes:
      label: Contribute
      description: Are you willing to submit the fix?
      options:
        - label: Yes, I want to contribute
          required: true
